### ISSUE TITLE
Support for the (Tree)SummarizedExperiment data container

### ISSUE THREAD

**Issue by antagomir** [EBI-Metagenomics/MGnifyR#6]
I propose adding support for _(Tree)SummarizedExperiment_ data container that is an alternative to _phyloseq_ in the MGnifyR R package. 

We can open a Pull Request?

An increasing number of microbiome data analysis tools support the TreeSummarizedExperiment  ([Huang et al. 2021](https://f1000research.com/articles/9-1246)) and MultiAssayExperiment ([Ramos et al. 2017](https://aacrjournals.org/cancerres/article/77/21/e39/662607/Software-for-the-Integration-of-Multiomics)) data containers and the [curatedMetagenomicData](https://waldronlab.io/curatedMetagenomicData/) project has started to distribute the data in this format. Converters between the TreeSummarizedExperiment and phyloseq are available via the [mia R/Bioc](microbiome.github.io/mia) package, these are two alternative formats. We have created an online tutorial, [Orchestrating Microbiome Analysis with R/Bioconductor](microbiome.github.io/OMA/) around the TreeSummarizedExperiment framework.

**Comment by beadyallen** [comment]
I'm not familiar with (Tree)SummarizedExperiment, but from a quick glance it seems there's a simple phyloseq -> TSE converter function. Is there a reason that this wouldn't suffice? I think adding conversion examples in the documentation would be fine, but I'm reluctant to integrate another phyloseq equivalent before it's been proved in the field. Happy to be persuaded otherwise though :-)

**Comment by antagomir** [comment]
Ok, we are ready with the PR as discussed. 

The new upgraded version is available at this fork: (https://github.com/microbiome/MGnifyR).

Before we open a large PR it would be good to have a chat and decide together how to take this further; to merge or to diverge.

**Comment by artur-sannikov** [comment]
Hi, should this be closed? We get TSE objects from MGnifyR.
